### PR TITLE
UXUI-513 - Adding the Thomas Cook theme for Insurance Healix

### PR DESCRIPTION
**Pull request by jodiedoubleday**
#### What does this PR do? (please provide any background)
- Adds a Thomas cook theme to pattern library

#### What tests does this PR have?
None

#### How can this be tested?
You will need to clone the pattern library repo and change to branch `UXUI-513`
run `npm link ../brands/`
make sure you are on this branch in brands.
You should be able to just run pattern library using 
`npm start` and then go to `pages` and click on any of the healix pages and be happy

#### Screenshots / Screencast
screen shot 2016-02-12 at 09 42 32

#### What gif best describes how you feel about this work?
Celebrate

---

- [x] I have checked our general [contributing document](https://github.com/holidayextras/culture/blob/master/CONTRIBUTING.md) and the project specific [contributing document](../blob/master/CONTRIBUTING.md) (if present) and I'm happy for this to be reviewed.

#### Reviewers

**Review 1**
- [ ] :+1:

**Review 2** \*
- [x] :+1:

**Review 3** _(optional)_
- [ ] :+1:

By adding a +1 you are confirming you have...
- Witnessed the work behaving as expected (this could be on the author's machine or screencast).
- Checked for coding anti-patterns.
- Checked for appropriate test coverage.
- Checked all the tests are passing.

\*  for HX this review must be completed by an SE, SA or Project Guru

### CODE REVIEW

**Comment by GeorgeF72** [comment]
:one:

**Comment by GeorgeF72** [comment]
Not sure how much of problem it is, but it looks a little odd for the search bar to not line up with the select or finish buttons: http://grab.by/O5dY

**Comment by HeinBehrenshx** [comment]
:+1:

**Comment by jodiedoubleday** [comment]
@GeorgeF72 yea I have the same horrible dread when i see it not aligned, however the Healix site is pretty much all built in tables and they have left a few blank cells in the layout.

I tried some css to hide all blank table cells which worked in some cases, but in others the table cells looked empty but instead was full of hidden things so the CSS trick didn't work.

**Comment by GeorgeF72** [comment]
:+1:

**Pull request merged**
