### PR TITLE
roll out the new logo everywhere

### PR DESCRIPTION
**Pull request by elliottcrush**
#### What does this PR do? (please provide any background)

Says. Tin. What. Does. On. It. The

#### How can this be tested?
`cd pattern-library && npm link ../brands`

#### What gif best describes how you feel about this work?

- [x] I have checked our general [contributing document](https://github.com/holidayextras/culture/blob/master/CONTRIBUTING.md) and the project specific [contributing document](../blob/master/CONTRIBUTING.md) (if present) and I'm happy for this to be reviewed.

---

**Reviewer**
- [ ] :+1:
- [ ] UXUI Team :+1:
- [ ] I don't think this PR needs any additional reviewers

By adding a +1 you are confirming you have...
- Witnessed the work behaving as expected (this could be on the author's machine or screencast).
- Checked all the work locally on pattern library.

---

### CODE REVIEW

**Comment by jodiedoubleday** [comment]
We include the non @2x version, but then we don't use it?

**Comment by elliottcrush** [comment]
Its optional. We don't actually use the variable defined as `@logo` anyway. All applications override it. I merely just want this logo in the CDN

**Comment by jodiedoubleday** [comment]
so future work would be to use the 2x when appropriate and the 'other' everywhere else

**Comment by stuartgiles** [comment]
Happy with this. Once the asset is on a live CDN I'd like the brand to point to the file by default in variables.less so the apps don't need to over ride it.

**Pull request merged**
