### PR TITLE
UXUI-573 | Adding globals into brands

### PR DESCRIPTION
**Pull request by elliottcrush**
#### What does this PR do? (please provide any background)
This PR addresses some concerns we've been having recently towards the branding structure thats implemented across HX. We need a global place to store styling that's perhaps not been covered by bootstrap or extra features that we want to introduce that are inherited across the brands. This is not a replacement for Toolkit component styling, it merely plugs the holes missed by bootstrap whilst attending to some of our specific application needs.

#### What tests does this PR have?
None :( 

#### How can this be tested?
Checkout the brands repo locally. NPM link into Pattern Library and double check the global files are compiling in the terminal.

#### What gif best describes how you feel about this work?
 -> Came up for globe search, don't hate me.

---

- [x] I have checked our general [contributing document](https://github.com/holidayextras/culture/blob/master/CONTRIBUTING.md) and the project specific [contributing document](../blob/master/CONTRIBUTING.md) (if present) and I'm happy for this to be reviewed.

#### Reviewers

**Review 1**
- [x] :+1:

**Review 2** \*
- [x] :+1:

**Review 3** _(optional)_
- [ ] :+1:

By adding a +1 you are confirming you have...
- Witnessed the work behaving as expected (this could be on the author's machine or screencast).
- Checked for coding anti-patterns.
- Checked for appropriate test coverage.
- Checked all the tests are passing.

\*  for HX this review must be completed by an SE, SA or Project Guru

### CODE REVIEW

**Comment by elliottcrush** [comment]
Keen for your thoughts, @nassimdonald nickphillipps @stuartgiles @jodiedoubleday @nickine

This kind of work is installable in applications, my first idea is to just move the already modularised tile styling for tripapp into the directory. Meaning we can reduce the size of the tripapp repo and better focus our attention on styling PR's as and when they come in. This work has really been undertaken off the back of [this](https://github.com/holidayextras/pattern-library/pull/51) which is also worth a checkout.

**Comment by stuartgiles** [comment]
Yeah this needs to be addressed!
We need a place for universal styles and helper classes which can be shared across all our brands and available to all projects. There are a bunch of examples in our issues list - https://github.com/holidayextras/brands/issues

For me there are three places this could go -
1. Brands > Global styles
2. Toolkit > Global styles
3. Another repo called something like "Bootstrap Extras"

I'm happy for them to go here at the moment because it focussed more attention on this repo.
(I guess it would be easy to move in the future should the need arise.)

I'll take one of the review spots now.

Thanks

**Comment by stuartgiles** [comment]
I've had an error on build

> Potentially unhandled rejection [2] .hx-font is undefined in file /Users/Stu/Sites/hx/pattern-library/node_modules/brands/brands/globals/src/less/tiles/_product.less line no. 281
> 

It looks like the product.less is using a mixin which hasn't yet been moved to Globals.

This could be removed for now, and refactored later.

**Comment by elliottcrush** [comment]
Thanks @stuartgiles have addressed your comments.

**Comment by nassimdonald** [comment]
:mag:

**Comment by nassimdonald** [comment]
Works well man, great work!

**Comment by stuartgiles** [comment]
This works for me now.
After a bunch of build errors I've finally got it to work :-)
Happy to :+1:

**Comment by elliottcrush** [comment]
Thanks guys :+1:

**Pull request merged**
