### PR TITLE
UXUI - 793 - Removing jira specific less from tripapp

### PR DESCRIPTION
**Pull request by h0rhay**
#### What does this PR do? (please provide any background)
This work cleans up a lot of tech debt on tripapp, and imports some of the less into this brands repo.

#### How can this be tested?
`cd pattern-library && npm link ../brands`

#### Any tech debt?
Nope, the opposite ;)

#### What gif best describes how you feel about this work?

- [ ] I have checked our general [contributing document](https://github.com/holidayextras/culture/blob/master/CONTRIBUTING.md) and the project specific [contributing document](../blob/master/CONTRIBUTING.md) (if present) and I'm happy for this to be reviewed.

---

**Reviewer**
- [ ] :+1:
- [ ] UXUI Team :+1:
- [ ] I don't think this PR needs any additional reviewers

By adding a +1 you are confirming you have...
- Witnessed the work behaving as expected (this could be on the author's machine or screencast).
- Checked all the work locally on pattern library.

---

### CODE REVIEW

**Comment by elliottcrush** [comment]
This work will also need a HX version bump

**Comment by circleBuildAgent** [comment]
****************************************************************************************

  <h4>✅  Warning: | All Good | ✅</h4>

  ****************************************************************************************

**Comment by circleBuildAgent** [comment]
****************************************************************************************

  <h4>✅  Warning: | All Good | ✅</h4>

  ****************************************************************************************

**Comment by circleBuildAgent** [comment]
****************************************************************************************

  <h4>✅  Warning: | All Good | ✅</h4>

  ****************************************************************************************

**Pull request merged**
