### PR TITLE
Travel Better

### PR DESCRIPTION
**Pull request by elliottcrush**
#### How can this be tested?
`cd pattern-library && npm link ../brands`

#### What gif best describes how you feel about this work?

- [ ] I have checked our general [contributing document](https://github.com/holidayextras/culture/blob/master/CONTRIBUTING.md) and the project specific [contributing document](../blob/master/CONTRIBUTING.md) (if present) and I'm happy for this to be reviewed.

---

**Reviewer**
- [ ] :+1:
- [ ] UXUI Team :+1:
- [ ] I don't think this PR needs any additional reviewers

By adding a +1 you are confirming you have...
- Witnessed the work behaving as expected (this could be on the author's machine or screencast).
- Checked all the work locally on pattern library.

---

### CODE REVIEW

**Comment by elliottcrush** [comment]
Creating a PR to test this work against the dependency tracking. FYI @stuartgiles and @jodiedoubleday

**Comment by circleBuildAgent** [comment]
<h2>Brand Version Notifications</h2><hr><h3>Application brand dependencies</h3><small><strong>A list of applications and whether or not they will automatically absorb your changes</strong></small></br><small>You're wanting to deploy <strong>3.0.0</strong></small><h4><i><a href="https://github.com/holidayextras/tripapplite">Tripapp</i></a> has the following brand dependencies:</h4><p>brandhx Version: <strong>^2.2.3</strong> ❌</p><h4><i><a href="https://github.com/holidayextras/static-site-generator-sites/tree/master/seo-hx-core">SEO Landing Pages</i></a> has the following brand dependencies:</h4><p>brandhx Version: <strong>2.1.6</strong> ❌</p><h4><i><a href="https://github.com/holidayextras/static-site-generator-sites/tree/master/hx-customer-contact">Manage My Booking</i></a> has the following brand dependencies:</h4><p>brandhx Version: <strong>^2.2.3</strong> ❌</p><h4><i><a href="https://github.com/holidayextras/static-site-generator-sites/tree/master/email-hx-landing">Email Landing Pages</i></a> has the following brand dependencies:</h4><p>brandhx Version: <strong>^2.2.3</strong> ❌</p><h4><i><a href="https://github.com/holidayextras/static-site-generator-sites/tree/master/system-maintenance">System Maintenance</i></a> has the following brand dependencies:</h4><p>brandhx Version: <strong>^2.2.3</strong> ❌</p><p><small><strong>Please consider these versions before merging</strong></small></p>

**Comment by circleBuildAgent** [comment]
<h2>Brand Version Notifications</h2><hr><h3>Application brand dependencies</h3><small><strong>A list of applications and whether or not they will automatically absorb your changes</strong></small></br><small>You're wanting to deploy <strong>3.0.0</strong></small><h4><i><a href="https://github.com/holidayextras/tripapplite">Tripapp</i></a> has the following brand dependencies:</h4><p>brandhx Version: <strong>^2.2.3</strong> ❌</p><h4><i><a href="https://github.com/holidayextras/static-site-generator-sites/tree/master/seo-hx-core">SEO Landing Pages</i></a> has the following brand dependencies:</h4><p>brandhx Version: <strong>2.1.6</strong> ❌</p><h4><i><a href="https://github.com/holidayextras/static-site-generator-sites/tree/master/hx-customer-contact">Manage My Booking</i></a> has the following brand dependencies:</h4><p>brandhx Version: <strong>^2.2.3</strong> ❌</p><h4><i><a href="https://github.com/holidayextras/static-site-generator-sites/tree/master/email-hx-landing">Email Landing Pages</i></a> has the following brand dependencies:</h4><p>brandhx Version: <strong>^2.2.3</strong> ❌</p><h4><i><a href="https://github.com/holidayextras/static-site-generator-sites/tree/master/system-maintenance">System Maintenance</i></a> has the following brand dependencies:</h4><p>brandhx Version: <strong>^2.2.3</strong> ❌</p><p><small><strong>Please consider these versions before merging</strong></small></p>

**Comment by circleBuildAgent** [comment]
<h2>Brand Version Notifications</h2><h4><i><a href="https://github.com/holidayextras/tripapplite">Tripapp</i></a> has the following brand dependencies:</h4><p>brandhx Version: <strong>^2.2.3</strong> ❌</p><h4><i><a href="https://github.com/holidayextras/static-site-generator-sites/tree/master/seo-hx-core">SEO Landing Pages</i></a> has the following brand dependencies:</h4><p>brandhx Version: <strong>2.1.6</strong> ❌</p><h4><i><a href="https://github.com/holidayextras/static-site-generator-sites/tree/master/hx-customer-contact">Manage My Booking</i></a> has the following brand dependencies:</h4><p>brandhx Version: <strong>^2.2.3</strong> ❌</p><h4><i><a href="https://github.com/holidayextras/static-site-generator-sites/tree/master/email-hx-landing">Email Landing Pages</i></a> has the following brand dependencies:</h4><p>brandhx Version: <strong>^2.2.3</strong> ❌</p><h4><i><a href="https://github.com/holidayextras/static-site-generator-sites/tree/master/system-maintenance">System Maintenance</i></a> has the following brand dependencies:</h4><p>brandhx Version: <strong>^2.2.3</strong> ❌</p><p><small><strong>Please consider these versions before merging</strong></small></p>

**Comment by circleBuildAgent** [comment]
<h2>Brand Version Notifications</h2><hr><h3>Application brand dependencies</h3><small><strong>A list of applications and whether or not they will automatically absorb your changes</strong></small></br><small>You're wanting to deploy <strong>3.0.0</strong></small><h4><i><a href="https://github.com/holidayextras/static-site-generator-sites/tree/master/seo-hx-core">SEO Landing Pages</i></a> has the following brand dependencies:</h4><p>brandhx Version: <strong>2.1.6</strong> ❌</p><h4><i><a href="https://github.com/holidayextras/static-site-generator-sites/tree/master/email-hx-landing">Email Landing Pages</i></a> has the following brand dependencies:</h4><p>brandhx Version: <strong>^2.2.3</strong> ❌</p><h4><i><a href="https://github.com/holidayextras/tripapplite">Tripapp</i></a> has the following brand dependencies:</h4><p>brandhx Version: <strong>^2.2.3</strong> ❌</p><h4><i><a href="https://github.com/holidayextras/render">Render</i></a> has the following brand dependencies:</h4><h4><i><a href="https://github.com/holidayextras/trip-planner">Trip Planner</i></a> has the following brand dependencies:</h4><p>brandhx Version: <strong>^2.2.2</strong> ❌</p><h4><i><a href="https://github.com/holidayextras/static-site-generator-sites/tree/master/hx-customer-contact">Manage My Booking</i></a> has the following brand dependencies:</h4><p>brandhx Version: <strong>^2.2.3</strong> ❌</p><h4><i><a href="https://github.com/holidayextras/static-site-generator-sites/tree/master/system-maintenance">System Maintenance</i></a> has the following brand dependencies:</h4><p>brandhx Version: <strong>^2.2.3</strong> ❌</p><h4><i><a href="https://github.com/holidayextras/tripapp-cordova">Mobile Booking App</i></a> has the following brand dependencies:</h4><p>brandhx Version: <strong>^2.2.1</strong> ❌</p><h4><i><a href="https://github.com/holidayextras/cordova-countdown">Mobile Countdown App</i></a> has the following brand dependencies:</h4><p><small><strong>Please consider these versions before merging</strong></small></p>

**Pull request closed without merging**
